nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

Appbar 제목 설정
장바구니 아이콘 생성
장바구니 페이지로 이동 기능
장바구니에 담는 기능
1차적으로 화면 구성

[add] detail파일 생성

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart.dart

[add]Shopping-Cart-body

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

[add] my_orders_page to project

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

[fix] shoppingcart

---

nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/background_photo.dart

BackgroundPhoto, JaketPhoto 클래스 파일을 분리했습니다

[modify]regist_page 함수 구조 개선

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

[feat] 장바구니 기능 추가

---

nakwon_online_shoppingmall/lib/main.dart
nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/background_photo.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/jaket_photo_button.dart

- 배경에 흐리게 깔리는 꾸미기용 이미지 추가
- BackdropFilter - ImageFilter.blur 속성 이용했습니다.
- 이미지 업로드 영역에 아이콘(photo_camera) 추가

[modify] 이미지 업로드 영역 UI 개선

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart
nakwon_online_shoppingmall/lib/pages/order/order.dart

- 장바구니에서 값을 받아올 때 사용할 클래스 파일(order.dart)생성
- my_orders_page.dart를 StatefulWidget으로 변경

[add] order.dart to project

---

nakwon_online_shoppingmall/lib/album.dart
nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

- Album class 추가
- my_orders_page.dart 내에서 받아올 객체를 order에서 album으로 변경

[add] album.dart to project

---

nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/info_textField.dart

/pages/regist/widgets/ 에 정보 입력 박스용 위젯인 **InfoTextField** 클래스를 만들었습니다.
``info_textField.dart`` 파일에 있습니다.
받으려는 데이터의 종류(가수 이름, 가격 등)를 ``String type 매개변수``로 받고,
데이터 이름과 텍스트필드 상자를 리턴합니다.
패딩 : 30
제목 부분 텍스트 : 사이즈 16, 왼쪽정렬
textField : BorderRadius 10 , 테두리 width 1.0 색상 Colors.grey[300]!

[add]정보 입력 위젯 InfoTextField  추가

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart

[add]ShoppingCartPageUI

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

[feat] appBar에 홈버튼 추가

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

[fix] 장바구니 이동경로 수정

---

nakwon_online_shoppingmall/lib/pages/home/home_page.dart

album 클래스 구조따라서 메인화면 데이터 만들어서 그 데이터로 화면에 뿌려지게 코드를 짜보았습니다.

[feat] 메인화면에서 데이터 구성, 데이터 연동

---

nakwon_online_shoppingmall/lib/pages/home/home_page.dart

Album 클래스에 상품 설명을 저장하는 <String> description 변수를 추가했습니다.
HomePage 에서 Album 변수를 만드는 부분에 적용 완료했습니다.

[fix]Album 클래스 구조 수정

---

nakwon_online_shoppingmall/lib/main.dart
nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart

- 상품 등록하기 버튼을 생성했습니다.
- 정보를 모두 입력했을 시 Album 객체를 만들어 pop합니다.
- [TODO]정말로 등록할지 묻는 확인 팝업 제작
- 정보를 모두 입력하지 않으면 CupertinoAlert를 띄웁니다.
- 상품 등록하기 버튼이 화면 세로 영역을 벗어나서, 정보 입력하는 부분을 스크롤 안에 넣어줬습니다.
- 추가로 appbar에 앱 이름을 표시하지 않고 있어서 넣어줬습니다.

[add]상품 등록하기 버튼 설정

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

[feat] 구매목록페이지 비었을 때 화면에 텍스트 표시

---

nakwon_online_shoppingmall/lib/main.dart
nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart
nakwon_online_shoppingmall/lib/theme.dart

- lib 디렉토리에 theme.dart 파일 추가했습니다.
- 적용 내용 : colorScheme 생성, elevated button 스타일 지정(모서리 둥글게 20), scaffold 배경색 Colors.white로 지정
- main 빌더에서 만든 테마 적용하도록 수정했습니다.
- ShoppingcartPage 버튼 코드 참고해서 RegistPage의 버튼 형식을 통일해줬습니다.
- 추후에 DetailPage의 버튼도 통일하면 좋을 것 같습니다.

[add] 테마 기능 추가

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

import album추가
홈페이지랑 appbar 맞춤

[fix] album

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

[Comment] 구매목록 페이지 주석 추가

---

nakwon_online_shoppingmall/lib/pages/home/home_page.dart
nakwon_online_shoppingmall/pubspec.lock
nakwon_online_shoppingmall/pubspec.yaml

album 리스트 목록 추가
floating 버튼을 누르면 메뉴가 표시되고 구매목록, 추가버튼 나오도록 수정

[feat] 리스트 내용추가, flating버튼에 추가, 구매목록 이동 추가

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart
nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

장바구니에 담기 눌렀을때 장바구니에 넣는 기능 추가
shopping_cart_page에서 인자로 받는 cartItems 정의

[feat] 장바구니에 넣는 기능 추가

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart
nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

1.detail_page에서 shopping_cart_page List로 넘겨주는 기능 추가
2.AppBar 뒤로가기 버튼 수정

[add]cartFeature7

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart
nakwon_online_shoppingmall/lib/pages/order/widgets/order_box.dart

- 장바구니에서 구매목록 페이지로 넘길 때 음반 개수 함께 받아오도록 변경
- 앱바에 홈 아이콘 색상 변경

[fix] 장바구니에서 음반 개수 함께 받아오도록 변경

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

장바구니에 담기를 여러번 눌렀을때 수량이 올라가는게 아닌 앨범이 여러개 생성됨
이미 담긴 앨범이 있으면 수량만 올라가게 수정

[feat] 장바구니에 추가기능

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart
nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart
nakwon_online_shoppingmall/lib/pages/order/widgets/order_box.dart

- 장바구니에서 구매목록으로 데이터 넘겨줄 때 오류 수정

[fix] 구매목록으로 데이터 넘겨줄 때 오류 수정

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

[modify] 뒤로가기, 장바구니 아이콘

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart
nakwon_online_shoppingmall/lib/pages/detail/widgets/detail_image_box.dart
nakwon_online_shoppingmall/lib/pages/home/widgets/image_box.dart

[fix] DetailPage 이미지 업로드 방식 변경

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart

1.assets, file 구별하여 장바구니 앨범사진 표시
2.장바구니 노래-가수 UI수정

[add]cartFeature10

---

nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart

- myOrders 페이지의 뒤로가기 버튼 색상 흰색으로 변경

[feat] 뒤로가기 버튼 색상 변경

---

nakwon_online_shoppingmall/lib/pages/detail/detail_page.dart

[modify] 장바구니에 담기 버튼

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart
nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart
nakwon_online_shoppingmall/lib/pages/order/saved_order.dart

- 구매목록 페이지에서 홈 화면으로 나가도 구매 목록 유지되게 수정

[fix] 구매 목록 유지 안되는 버그 수정

---

nakwon_online_shoppingmall/analysis_options.yaml
nakwon_online_shoppingmall/lib/pages/home/home_page.dart
nakwon_online_shoppingmall/lib/pages/regist/regist_page.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/info_textField.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/price_textField.dart
nakwon_online_shoppingmall/lib/pages/regist/widgets/regist_button.dart

- 텍스트필드에 라벨 추가
- 상품 가격에는 숫자만 입력되도록 수정

[modify] 상품 등록 텍스트필드 수정

---

nakwon_online_shoppingmall/lib/pages/cart/shopping_cart_Page.dart
nakwon_online_shoppingmall/lib/pages/order/my_orders_page.dart
nakwon_online_shoppingmall/lib/pages/order/saved_order.dart
nakwon_online_shoppingmall/lib/pages/order/widgets/order_box.dart

[feat] 구매 목록 리스트에 구매 시간 추가
